# Generated by Django 5.2.5 on 2025-08-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
